<a href="https://colab.research.google.com/github/vyakhyaagoyal/DL_Lab_V/blob/main/DL_lab_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
np.random.seed(42)

print("NumPy version:", np.__version__)
print("Seaborn version:", sns.__version__)

NumPy version: 2.0.2
Seaborn version: 0.13.2


In [ ]:
# A one-dimensional NumPy array (vector)
x = np.array([2, 4, 6, 8, 10], dtype=float)

print("x =", x)
print("shape =", x.shape)
print("size =", x.size)
print("ndim =", x.ndim)
print("dtype =", x.dtype)

x = [ 2.  4.  6.  8. 10.]
shape = (5,)
size = 5
ndim = 1
dtype = float64


In [ ]:
# Two-dimensional array (matrix)
A = np.array([[1, 2, 3],
[4, 5, 6]])

# Row vector and column vector
row_vector = np.array([[1, 2, 3, 4]])
column_vector = np.array([[1], [2], [3], [4]])

print("A:\n", A)
print("A shape:", A.shape)
print("A size:", A.size)
print("A ndim:", A.ndim)
print("Row vector shape:", row_vector.shape)
print("Column vector shape:", column_vector.shape)

A:
 [[1 2 3]
 [4 5 6]]
A shape: (2, 3)
A size: 6
A ndim: 2
Row vector shape: (1, 4)
Column vector shape: (4, 1)


In [ ]:
Z = np.zeros((3, 4)) # zero matrix
O = np.ones((2, 5)) # one matrix
I = np.eye(4) # identity matrix
D = np.diag([2, 4, 6, 8]) # diagonal matrix
C = np.full((2, 3), 7) # constant matrix
R = np.random.randn(3, 2) # standard normal random values
U = np.random.rand(3, 2) # uniform random values in [0, 1)

print("Zero matrix:\n", Z)
print("One matrix:\n", O)
print("Identity matrix:\n", I)
print("Diagonal matrix:\n", D)
print("Constant matrix:\n", C)
print("Random normal matrix:\n", R)

Zero matrix:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
One matrix:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Diagonal matrix:
 [[2 0 0 0]
 [0 4 0 0]
 [0 0 6 0]
 [0 0 0 8]]
Constant matrix:
 [[7 7 7]
 [7 7 7]]
Random normal matrix:
 [[ 0.49671415 -0.1382643 ]
 [ 0.64768854  1.52302986]
 [-0.23415337 -0.23413696]]


In [ ]:
M = np.array([[10, 11, 12, 13],
[20, 21, 22, 23],
[30, 31, 32, 33],
[40, 41, 42, 43]])

print("First element:", M[0, 0])
print("Last element:", M[-1, -1])
print("Second row:", M[1, :])
print("Third column:", M[:, 2])
print("Top-left 2 x 2 submatrix:\n", M[0:2, 0:2])
print("Rows 2 to 4, columns 2 to 4:\n", M[1:4, 1:4])
print("Every alternate row:\n", M[::2, :])

First element: 10
Last element: 43
Second row: [20 21 22 23]
Third column: [12 22 32 42]
Top-left 2 x 2 submatrix:
 [[10 11]
 [20 21]]
Rows 2 to 4, columns 2 to 4:
 [[21 22 23]
 [31 32 33]
 [41 42 43]]
Every alternate row:
 [[10 11 12 13]
 [30 31 32 33]]


In [ ]:
P = np.array([[1, 2], [4, 5]])
Q = np.array([[10, 20],[40, 50]])
print("P + Q:\n", P + Q)
print("P * Q (element-wise):\n", P * Q)
print("P @ Q (element-wise):\n", P @ Q)
print("P ** 2:\n", P ** 2)
print("Transpose of P:\n", P.T)

# Broadcasting: add one bias value to every row
bias = np.array([[100], [200]])
print("P + bias:\n", P + bias)

# Reshaping
v = np.arange(1, 13)

print("Reshaped 3 x 4:\n", v.reshape(3, 4))
print("Flattened array:", P.flatten())

P + Q:
 [[11 22]
 [44 55]]
P * Q (element-wise):
 [[ 10  40]
 [160 250]]
P @ Q (element-wise):
 [[ 90 120]
 [240 330]]
P ** 2:
 [[ 1  4]
 [16 25]]
Transpose of P:
 [[1 4]
 [2 5]]
P + bias:
 [[101 102]
 [204 205]]
Reshaped 3 x 4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flattened array: [1 2 4 5]


In [ ]:
#task 6.1(a)
print("Array v:",v)

Array v: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
#task 6.1(b)
scores=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
# Broadcasting: add one bias value to every row
bias1 = np.array([[100], [200], [300]])
print("scores + bias1:\n", scores + bias1)

scores + bias1:
 [[101 102 103 104]
 [205 206 207 208]
 [309 310 311 312]]


In [ ]:
#task 6.1(c)
tensor=np.array([[[1,2,3,4],[4,5,6,7],[7,8,9,10]],
                [[7,8,9,10],[12,13,14,15],[16,17,18,19]]])
print(tensor)
print("Shape:",tensor.shape)
print("Dimension:",tensor.ndim)

[[[ 1  2  3  4]
  [ 4  5  6  7]
  [ 7  8  9 10]]

 [[ 7  8  9 10]
  [12 13 14 15]
  [16 17 18 19]]]
Shape: (2, 3, 4)
Dimension: 3


In [ ]:
#task 6.1(c)
arr=np.arange(1,25)
print(arr)
tensor1=arr.reshape(2,3,4)
print(tensor1)
print("Shape:",tensor1.shape)
print("Dimension:",tensor1.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape: (2, 3, 4)
Dimension: 3


In [ ]:
#task 6.1(d)
a=np.array([[1,2,3,4,5],[3,4,5,6,7]])
trans=a.T
print(trans)
print("Shape of original matrix:",a.shape)
print("Shape of transpose matrix:",trans.shape)

[[1 3]
 [2 4]
 [3 5]
 [4 6]
 [5 7]]
Shape of original matrix: (2, 5)
Shape of transpose matrix: (5, 2)


In [ ]:
#task 7
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("np.dot(a, b) =", np.dot(a, b))
print("a @ b =", a @ b)

np.dot(a, b) = 32
a @ b = 32


In [ ]:
# A row-like 1D vector with 3 elements
v = np.array([1, 2, 3])

# Matrix with shape (3, 2)
N = np.array([[1, 2],
[3, 4],
[5, 6]])

print("v shape:", v.shape)
print("N shape:", N.shape)
print("v @ N shape:", (v @ N).shape)
print("v @ N =", v @ N)

# Matrix-vector product: N.T has shape (2, 3), v has shape (3,)
print("N.T @ v =", N.T @ v)

v shape: (3,)
N shape: (3, 2)
v @ N shape: (2,)
v @ N = [22 28]
N.T @ v = [22 28]


In [ ]:
A = np.array([[1, 2, 3],
[4, 5, 6]]) # shape (2, 3)
B = np.array([[1, 0],
[0, 1],
[1, 1]]) # shape (3, 2)

C = A @ B
print("A shape:", A.shape)
print("B shape:", B.shape)
print("C = A @ B:\n", C)
print("C shape:", C.shape)

A shape: (2, 3)
B shape: (3, 2)
C = A @ B:
 [[ 4  5]
 [10 11]]
C shape: (2, 2)


In [ ]:
#task 7.1(a)
p = np.array([2, -1, 3, 0])
q = np.array([4, 5, -2, 1])
s=p@q
print("Dot product of p and q:",s)
print(np.dot(p,q))

Dot product of p and q: -3
-3


In [ ]:
#task 7.1(b)
r=np.array([1,2,3,4])
s=np.array([[1,2,3],[2,3,4],[3,4,5],[4,5,6]])
output=r@s
print(output)
print(output.shape)

[30 40 50]
(3,)


In [ ]:
#task 8
#l1 - manhattan distance with order=1
#l2 - euclidean distance with order=2
v = np.array([3, 4, 12], dtype=float)

l2_manual = np.sqrt(np.sum(v ** 2))
l2_numpy = np.linalg.norm(v, ord=2)

print("Manual L2 norm:", l2_manual)
print("NumPy L2 norm:", l2_numpy)

# Unit vector in the same direction
v_unit = v / np.linalg.norm(v)
print("Unit vector:", v_unit)
print("L2 norm of unit vector:", np.linalg.norm(v_unit))

Manual L2 norm: 13.0
NumPy L2 norm: 13.0
Unit vector: [0.23076923 0.30769231 0.92307692]
L2 norm of unit vector: 1.0
